language: node_js
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
before_install:
  - npm install -g gulp
install:
  - npm install
script:
  - npm run test
  - npm run coveralls
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
